version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: student-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  student-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-management
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
    ports:
      - "8089:8089"

volumes:
  mysql-data:
